export const districtBranch={
    "centeralFinfine":[
      'Aba Mela' ,
      'Aba Nefso', 
      'Abdisa Aga', 
      'Agemsa',
      'Aster Gano', 
      'Badho Dachas', 
      'Baro Korma', 
      'Birbirsa', 
      'Birmaji', 
      'Bombtera', 
      'Catherine Hamlin',
      'Chachu',
      'Chafe Anane', 
      'Chafe Muda', 
      'Churchill' ,
      'Dalatti', 
      'Debasso',
      'Dolo Bidena', 
      'Edao Boru', 
      'Finfine', 
      'Gebeyehu Gurmu' ,
      'Gojam Berenda' ,
      'Hailamariam Gamada',
      'Haile Fida' ,
      'Hilal' ,
      'Hurufa Rare' ,
      'Jimma Sanbate' ,
      'Kebena' ,
      'Kello Mesqela' ,
      'Kersa Main' ,
      'Mechaf Tulama' ,
      'Melka Oboshe', 
      'Merkato ',
      'Mesalemia' ,
      'Meskel Flower' ,
      'Mina ',
      'Oda' ,
      'Prof. Gebissa',
      'Robale' ,
      'Sheger' ,
      'Sinqee' ,
      'Sora Lume' ,
      'Sulula Garbi' ,
      'Ummu-Ayman',
      'Wayyu', 
      'Wirtu Merkato' ,
      'Yai Goro' ,
      "Yai Gulele" ,
      
      ],
      
      "adama":[
       "Adama" ,
       "Adea ",
       "Artu ",
       "Awash Melkasa ",
       "Awash Sebat Kilo" ,
       "Baka Ijo Eco ",
       "Barecha", 
       'Bedhatu ',
       'Bilal' ,
       'Bishoftu ',
       'Boku Shenen', 
       'Bole Nurahera' ,
       'Boset' ,
       'Bote' ,
       'Burka ',
       'Chafe', 
       'Dabe Soloke' ,
       'Dagaga',
       'Dambala micro', 
       'Derartu Tulu', 
       'Dhadacha Arara',
       'Dhaka Adi',
       'Dire Eco' ,
       'Dire Jitu', 
       'Ela Bela',
       'Ganda Hara', 
       'Gara Baru', 
       'Godino Eco', 
       'Gumbichu', 
       'Gurmu', 
       'Hadho Eco', 
       'Haro Adi', 
       'Hawas',
       'Hora Arsedi', 
       'Karayu' ,
       'Kilole' ,
       'Kiltu Lume', 
       'Koka',
       'Liban Chukala',
       'Lugo',  
      ' Meki',
       'Mojo', 
       'Oda Bokota', 
       'Qechema', 
       'Qoche',
       'Qurqura', 
       'Torban Garba', 
       'Torban Obo', 
       'Tullu Jada Eco', 
       'Wanji', 
      
      ],
      "asalla":[
      'Abba Jama',
      "Abomsa",
      "Addele",
      "Anole",
      "Arboye",
      "Asela",
      "Badr",
      "Bale Gesgar",
      "Bokoji",
      "Boru Jawi",
      "Chilalo",
      "Chole",
      "Digalu",
      "Diksis",
      "Dodota",
      "Ego",
      "Eteya",
      "Golja",
      "Gololcha",
      "Habe",
      "Halila",
      "Huruta",
      "Kersa Arsi",
      "Kula",
      "Lenjiso Diga",
      "Lole Bulchana eco",
      "Meraro",
      "Negelle Arba Gugu",
      "Ogolcho",
      "Robe Dedea",
      "Sagure",
      "Salahadin Ali-Ayub",
      "Semira Kolba",
      "Shirka",
      "Siltana",
      "Sire Arsi",
      "Tijo",
      "Tiyo",
      "Xicho",
      ],
      
      "bale":[
      "Agarfa",
      "Ali",
      "Burka Walabu",
      "Dinsa Eco",
      "Dinsho",
      "Dolo Mana",
      "Dolosebro",
      "Gasara",
      "GeneralWakoGutu",
      "Ginnir",
      "Goba",
      "Goro",
      "Harana Buluq",
      "Haro Dumal",
      "Holqa Sofumer Eco",
      "Jarra",
      "Mada Walabu",
      "Maliyu",
      "Oda Roba Eco",
      "Rayan",
      "Rayitu",
      "Robe",
      "Sanate",
      "Selam",
      "Selka Bakaye Eco",
      "Sinana",
      "Sofomar",
      ],
      
      "chiro":[
      'Al Bukhari',
      'Anchar',
      'Arba Eco""',
      'Assebot New',
      'Baroda',
      'Bedessa',
      'Boke Tiko',
      'Burqa Dhintu  New',
      'Chiro',
      'Deder',
      'Defo Eco',
      'Dhumuga',
      'Doba',
      'Furqan',
      'Gara Muktar Eco',
      'Garu hira',
      'Gelemeso',
      'Gemechis',
      'Hardim Eco',
      'Haro Chercher',
      'Hirna',
      'Jaja',
      'Kamona',
      'Kara Makala Eco',
      'Kara Mile',
      'Kobo',
      'Mechara',
      'Melka Balo',
      'Michata',
      'Miesso',
      'Milqaye',
      'Murtiguto',
      'Oda Bultum',
      'Sheik Moh. Reshad',
      'Shenen dhugo',
      'Soqa',
      'Tullo',
      ],
      
      "dirreDawa":[
          'Abdi Qophe',
      'Abubeker Al-Siddiq',
      'Afren Kelo ',
      'Ahmed Imam' ,
      'Arefa' ,
      'Aw-Abadir',
      'Babile', 
      'Badano' ,
      'Bekerware' ,
      'Bereka' ,
      'Biftu',
      'Bulullo ',
      'Burka Tirtira' ,
      'Chalanqo', 
      'Chinaksen',
      'Dire Dawa',
      'D/Dawa Industry Park',
      'Dire Xayara Eco',
      'DireDawa Rashotel',
      'Elemo Qiltu' ,
      'Fachatu Eco',
      'Falana Eco', 
      'Fedis' ,
      'Fugnan Bira', 
      'Gara Muleta' ,
      'Gode ',
      'Goro Muti' ,
      'Greek Camp' ,
      'Hafatessa ',
      'Haramaya',
      'Hikma',
      'Hundene' ,
      'Imam A Mesjid' ,
      'Iqra',
      'Jahan Jarso' ,
      'Jara Abageda ',
      'Jigjiga',
      'Kali' ,
      'Kefira ',
      'Kombolcha',
      'Kurfa Challe',
      'Laga Oda',
      'Maya Eco',
      'Mayu Muluke',
      'Medinat Al-Mun',
      'Megalla ',
      'Melka Jebdu', 
      'Midhega',
      'Mustafa Harawe ',
      'Qulubi', 
      'Ramadan',
      'Sabian',
      'Sheik Bek/Sapello',
      'Taiwan', 
      'Togo Wuchale',
      'Weltea' ,
      ],
      
      "eastFinfine":[
          'Abebech Gobena',
      'Abebie Tufa',
      'Agari Tullu',
      'Akaki',
       'Baro Tumsa' ,
      'Beshale',
       'Bole Airport ',
      'Bole Arabsa',
      'Bole Atlas',
      'Bole Bulbula',
      'Bole Lami',
      'Bole Medan',
      'Bole Michael',
      'Bole Ruwanda',
      'Boru Bilo',
      'Burqa Shobe',
      'Col Alamu Qixxessa',
      'Damo Dadi',
      'Dhaga Bora',
      'Dukem Industry',
      'Dulo',
      'Eka Abado',
      'Erer',
      'Figa',
      'Gada Melba',
      'Gadisa Birru',
      'Gara Bushu',
      'Gara Duba',
      'Gawassa',
      'Gelan',
      'Gerji',
      'Gurd Shola',
      'Haile Gebre',
      'Handura Tulama',
      'Haramain',
      'Harbu',
      'Hayahulet Mazo',
      'Jate',
      'Karra Qallu',
      'Koticha',
      'Koye Fache',
       'Kura Jida' ,
      'Lami Industrial',
      'Lauret Tsegaye',
      'Lema Guya',
      'Lemo',
      'Malka Shane',
      'Mammo Mazammir',
      'Mari Luqe',
      'Melba',
      'Migira Micro',
      'Oda Nabe',
      'Sadan Ekka',
      'Saris',
      'Shabu Ejersa',
      'Shala',
      'Tirunesh Dibaba',
      'Tulu Dimtu',
      'Wami Biratu',
      'Wara Ganu',
      'Xadacha',
      'Yuba',
      ],
      
      "hawasa":[
      'Adola',
      'Alamura',
      'Aleta Wondo',
      'Alnasir Sub',
      'Bensadaye',
      'Beriso Dukale Micro',
      'Birbirsa Kojowa  eco',
      'Bore',
      'Bule Hora',
      'Chelektu',
      'Chuko',
      'Daka',
      'Dari kidame  eco',
      'Deraro',
      'Dilla',
      'Dolo ado Sub', 
      'El-waye eco',
      'Fura',
      'Gedeb',
      'Gomole  eco',
      'Gudatu Robale eco',
      'Harakelo',
      'Hawassa',
      'Haya Dima',
      'lakku',
      'Madha Galma Micro',
      'Moyale Sub',
      'Negelle Borena',
      'Nur',
      'Odoshakiso',
      'Qarcha',
      'Shafeta',
      'Sumuda',
      'Tabor',
      'Taltale ',
      'Tulufarda ',
      'Uraga',
      'Wadera Micro ',
      'Warka',
      'Yabelo',
      'Yirgachefe',
      'Yirgalem',
      ],
      
      "Hosana":[
          "Arba Minch",
      "Areka",
      "Boditi",
      "Bonosha",
      "Bui",
      "Butajira",
      "Conolel Bezabih Petros",
      "Damboya",
      "Dawuro",
      "Doyo Gena",
      "Durame",
      "Enseno",
      "Geja Geribo",
      "Gesupa",
      "Hadero",
      "Halaba Kulito",
      "Hambecho Eco",
      "Hamus Gebeya Eco",
      "Homecho",
      "Hosana",
      "Jajura",
      "Kela",
      "Konso",
      "Koshe Mareko",
      "Kuno Gebeya Eco",
      "Lisana",
      "OMER IBN AL-KHATTAB",
      "Sankura",
      "Sechduna",
      "Shinshicho",
      "Shonkola",
      "Tona",
      "Tunto Eco",
      "Wolayita Soddo",
      "Darge",
      "Wolkite",
      
      ],
      
      "jimma":[
           "Aba Jifar", 
       "Agaro",
       "Alge Sachi", 
       "Asendabo", 
       "Awetu", 
       "Bedelle",
       "Bonga", 
       "Botor Xolay ",
       "Bure Illu", 
       "Chora", 
       "Dambi", 
       "Darimu", 
       "Dedo",
       "Dusta Eco",
       "Gachi",
       "Gambella", 
       "Gera", 
       "Gore", 
       "Hirmata",
       "Hurumu", 
       "Jiren", 
       "Limu Genet", 
       "Limu Seqa", 
       "Melka dabena", 
       "Meti", 
       "Mettu", 
       "Mizan Aman", 
       "New land", 
       "Omo Nada",
       "Saxama", 
       "Sedecha", 
       "Seglen Ilu",
       "Seka Chekorsa", 
       "Serbo", 
       "Shabe", 
       "Shenene Gibe", 
       "Sigimo", 
       "Sokoru",
       "Sor", 
       "Tepi", 
       "Tobba", 
       "Yayo", 
       "Yebu", 
      " yukiro kamise",
      ],
      
      "naqamte":[
          'Abasena',
      'Agamsa Migir',
      'Amuru',
      'Anfillo',
      'Anger Gute',
      'Anno',
      'Asosa',
      'Ayira',
      'Babo Gambel',
      'Bake Jamma',
      'Begi',
      'Bila',
      'Bokku',
      'Boneya Boshe',
      'Burqa Jato',
      'Chalalaqi',
      'Chanqa Birbir',
      'Chawaqa',
      'Dambi Dollo',
      "Fincha'a",
      'Ganji',
      'Gida Ayana',
      'Gidami', 
      'Gimbi',
      'Gudetu Arjo',
      'Guduru',
      'Guliso',
      'Hababo Gudur',
      'Harato',
      'Hawa Gelan',
      'Jimma Arjo',
      'Jimma Rare',
      'Kiltu Karra ',
      'Kiremu',
      'Komto',
      'Leka',
      'Leka Dulacha', 
      'Mandi',
      'Muka Arara ',
      'Nedjo',
      'Nekemte',
      'Nunu Kumba',
      'Oda Karra',
      'Oliqa Dingil',
      'Qebe',
      'Qeto Machara',
      'Sayo Nole',
      'Shambu',
      'Sibu Sire',
      'Tulu Gana',
      'Ukke',
      ],
      
      "northFinfine":[
           "Abichu Nya'a" ,
      'Adami',  
       'Addisu Gebeya',  
       'Akako',
       'Aleltu' , 
      'Asmerom',
       'Awaro',
       'Bakalcha', 
       'Bake', 
      'Bilile', 
       'Borri',  
       'Chafe Arara',  
       'Chancho',  
       'CMC',
       'Dale Dembel', 
       'Debre berhan', 
       'Dega Gora Eco',  
       'Derra',  
       'Didimtu',
       'Duber eco',
       'F/ Legasiyon', 
       'Fiche',  
       'Fitala',
      'Folle', 
       'Gachana', 
       'Gebra Guracha', 
       'Gora', 
       'Gulele',  
       'Hambiso Eco',
       'Harru Maru', 
       'Hidhabu Abote' ,
       'Hurufa farado', 
       'Kara Mexi',  
       'Karra Allo', 
       'Karra Xuxxo',  
       'Konno',
       'Kotobe',  
       'Kuyyu', 
       'Laga Bari', 
       'Lamberet',  
       'Lega bilawo', 
       'Lega Jidha', 
       'Lega Tafo',  
       'Madaro', 
       'Mujja',  
       'Muka Turi',  
       'Mulo', 
       'Raba dori', 
       'Raso',
       'Salgan Eggu',  
       'Sendafa Bake',  
       'Shararo',  
       'Shenen Jida',  
       'Sheno' , 
       'Shufune',  
       'Sululta', 
       'Tokumma',  
       'Tufa Muna',  
       'Tulu Fati' ,
       'Tulu Kurfo Ec', 
       'Wabari', 
       'Warra Jarso',  
       'Wasarbi',  
       'Yaya Gulale', 
       'Zerihun Wadajo',  
      ],
      
      "shashamanne":[
      'ADABA', 
      'AJE' ,
      'Allache',
       'AMAL', 
       'Ardaita eco friendly', 
       'ARSINEGELE', 
       'AWASHO', 
       'Batu', 
       'Birbirsa qaraxa' ,
       'BISHANGURACHA ',
       'Bulbula', 
       'Dida boqe',
       'DODOLA' ,
       'FEJIR' ,
      'HAMZA MESGID', 
       'HARA DEMBAL',  
       'HARUFA', 
       'HASASA',
       'HEBANARSI' ,
       'Heraro', 
       'IMAN',
       'KILTU DEMA',
       'KOFELE', 
       'KOKOSA',
       'KUYERA', 
       'Meja dema',
       'Melka oda', 
       'NaGELE HASASA', 
       'Negelle Metama Eco friendly', 
       'NESIHA', 
       'ODABILIBILA',
       'QORE',
       'Serofta Eco friendly', 
       'SHASHEMENE',
       'Uta kaka eco friendly', 
       'UTAWAYU', 
       'WARQA', 
      ],
      
      "southFinfine":[
           "Adadi Eco", 
       "Ali Bira", 
       "Asgori", 
       "Ayetu", 
       "Bakannisa", 
       "Bantu", 
       "Burka Wayu", 
       "Butta", 
       "Chalchali", 
       "Darraba Bido", 
       "Dawo", 
       "Ertu", 
       "Furi",
       "Gara Bolo", 
       "Gara Dhanqu", 
       "Gofa Gabriel",
       "Gofa Mazoria", 
       "Golbo", 
       "Gotera", 
       "Gudattu Qarsa Eco",
       "Guge", 
       "Halchisa", 
       "Haro Wanchi", 
       "Horsisa", 
       "Illanso",
       "Ittimako", 
       "Jahan Ameya", 
       "Jamo", 
       "Koromi", 
       "Labu", 
       "Lafto",
       "Laga Jaja",
       "Leman",
       "Lume",
       "Mako Bili", 
       "Marwa", 
       "Melka Hurbu", 
       "Merde",
       "Mogle", 
       "Nonno", 
       "Ochocha", 
       "Ona Jarsayu", 
       "Qacha", 
       "Qorke Karabu", 
       "Raphe", 
       "Roge",
       "Sadan Soddo", 
       "Sebeta Ayo", 
       "Sebeta Hawas", 
       "Soddo Dachi" ,
       "Soddo Garbo Eco" ,
       "Taji", 
       "Tiksa Jima", 
       "Torban Wale", 
       "Tullu Ejersa", 
       "Tulu Bolo", 
       "Tulu Dhertu", 
       "Urji",
       "Wasanu Dido", 
       "Wato", 
       "Weliso", 
       "Ya'i Melka", 
      ],
      
      "westFinfine":[
          'Aba Gemechis',
      'Abishe Gerba',
      'Abuna',
      'Ada Barga',
      'Ako Manoye' ,
      'Ambo',
      'Ansar',
      'Asgori-Suba Eco', 
      'Asko',
      'Axale Jatani',
      'Ayer Tena',
      'Bako Tibe',
      'Bethel',
      'Boke',
      'Boku Migra Bake',
      'Boru Joka',
      'Buludo',
      'Burayu',
      'Dire Hinchini' ,
      'Dire Sololiya',
      'Ebisa Adugna',
      'Ejere ',
      'Gafarsa Nono',
      'Gedo ',
      'Gefersa',
      'Ginchi',
      'Goro Qerensa',
      'Guddu',
      'Guder',
      'Guje',
      'Hayyu',
      'Holeta',
      'Ilu Gelan', 
      'Irbu',
      'Jagema Bedhane',
      'Jaldu',
      'Jibat',
      'Karra Qore',
      'Katta',
      'Kolfe',
      'Kolobo',
      'Kombe',
      'Kusaye',
      'Kutaye', 
      'Lega Saqo',
      'Liban Jawi',
      'Makkat Al Mukaram',
      'Melka Gefersa',
      'Meta Walkite', 
      'Midakegni',
      'Mogor',
      'Nejashi',
      'Oda Bisil',
      'Odo Liben',
      'Olonkomi', 
      'Qajela Doyo',
      'Qale',
      'Taqwa',
      'Wadessa',
      'Warqa Qore Eco',
      ],
      
      "bahirdar":[
      'Bahir Dar',
      'Bure',
      'D-Markos',
      'Dessie',
      'G-wuha',
      'Gondar',
      'Halal',
      'Kamise',
      'Metema',
      'M-Dawud',
      'Tana',
      'L.S-Alimirah',
      'Humera',
      'Wollo-Combolcha',
      'Injibara',
      ],
      
      "mekelle":[
      'Adigrat',
      'Adihaki',
      'Adwa',
      'Aksum',
      'Djibruk',
      'Enkodo',
      'Godena Selam',
      'Mekele',
      'Shire',
      'Wukre']
  }